DROP TABLE IF EXISTS CUSTOMER;
DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS ORDER;


CREATE TABLE CUSTOMER (
       ID INT NOT NULL AUTO_INCREMENT
     , FIRST_NAME VARCHAR(60) NOT NULL
     , LAST_NAME VARCHAR(40) NOT NULL
     , PRIMARY KEY (ID)
);

CREATE TABLE ORDER (
		ID INT NOT NULL AUTO_INCREMENT
     , PRIMARY KEY (ID)
);

CREATE TABLE PRODUCT (
		ID INT NOT NULL AUTO_INCREMENT
	 , NAME VARCHAR(60) NOT NULL
     , COST DOUBLE NOT NULL
     , PRIMARY KEY (ID)
);


