insert into customer (firstname, lastname, address, mobphone, email, specialinstructions, credit) values ('Bruce', 'Donald','57 Beach Rd, Albany', '02102539198', 'place234@thing.com', '', 5);
insert into customer (firstname, lastname, address, mobphone, email, specialinstructions, credit) values ('Blare', 'Richard','73 Station Pl, Wellsford', '0215539198', 'place56@thing.com', 'Money in letter box', 5);
insert into customer (firstname, lastname, address, mobphone, email, specialinstructions, credit) values ('Simon', 'Frank', '18 Name St, Whangarei', '0210253788', 'plac3e@thing.com', 'Leave by back door', 7);
insert into customer (firstname, lastname, address, mobphone, email, specialinstructions, credit) values ('Harry', 'Willford', '26 Age St, Auckland', '0210753788', 'plac98e@thing.com', '', -3);
insert into product (name, cost, description) values ('Dozen Eggs', 5, 'A dozen size 6 brown eggs');
insert into product (name, cost, description) values ('Half Dozen Eggs', 2.5, 'A half dozen size 6 brown eggs');
insert into product (name, cost, description) values ('Dozen Eggs-green', 8, 'A dozen size 6 green shelled eggs');
insert into product (name, cost, description) values ('Half Dozen Eggs-green', 4, 'A half dozen size 6 green shelled eggs');
insert into order_table (customer_id, product_id) values (1,1);
insert into order_table (customer_id, product_id) values (3,2);
insert into order_table (customer_id, product_id) values (2,1);
insert into order_table (customer_id, product_id) values (4,4);